### ISSUE TITLE
[feature] Card description for deck page.

### ISSUE THREAD

**Issue by FoxSquared** [blinpete/mtg-builder-next-13#2]
It would be nice if user could see a card description by clicking on it on deck page the same way as it works on deck editing page. 

Deck page. Cards are just images. When I click on it nothing happens.
![card_description](https://github.com/blinpete/mtg-builder-next-13/assets/41552528/322a47f1-efef-486d-ab39-8ded8a8f965d)

Deck editing page. When I click on the card I can see it description.
![card_description2](https://github.com/blinpete/mtg-builder-next-13/assets/41552528/5167fa30-0d1b-439f-b400-dcff00ef3aa4)

**Comment by blinpete** [comment]
@FoxSquared 
just merged PR #3, it'll get to production in a minute 🚀
Thank you for contributing!
